spring:
  application:
    name: demo


management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: "health,info,metrics,env,loggers"

springdoc:
  show-actuator: true
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
  paths-to-match: /api/v1/**